removed required for Custom/properties/custom
Error:  650:11  error  required-object-params     #/components/schemas/Custom/allOf/1 is defined as a required object, but no child fields are required
Error:  650:11  error  required-property-example  #/components/schemas/Custom/allOf/1/properties/custom is defined as a required object and is missing an example